#!/bin/bash

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in

  configure)
    echo "Configuring s2-server-ec."
    chmod 775 /etc/init.d/s2-server-ec
    systemctl daemon-reload
    systemctl enable s2-server-ec
    echo "Done."
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

