#!/bin/bash

set -e

case "$1" in
  remove|upgrade|deconfigure|purge)
    service s2-server-ec stop
    systemctl disable s2-server-ec
  ;;

  failed-upgrade)
  ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0

